id: opecha:P004134
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD137813
  title: རྭ་སྐོར་མཁན་ཆེན་ཐུབ་བསྟན་ནོར་བུའི་མཛད་རྣམ་དང་གསུང་ཆོས་ཕྱོགས་བསྡུས་དད་པའི་སྣང་བ་འདྲེན་པའི་འོད་སྣང་།
  volume: ''
  author: ''
