id: P004134
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD137813
  title: རྭ་སྐོར་མཁན་ཆེན་ཐུབ་བསྟན་ནོར་བུའི་མཛད་རྣམ་དང་གསུང་ཆོས་ཕྱོགས་བསྡུས་དད་པའི་སྣང་བ་འདྲེན་པའི་འོད་སྣང་།
  author: ''
  volumes:
    866796f5dd29457294e1156328e7df6c:
      image_group_id: I2PD19057
      title: ''
      volume_number: 1
      total_pages: 440
